# Generated by Django 5.2.4 on 2025-07-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Design', 'Design'), ('Marketing', 'Marketing')], max_length=50)),
                ('resource_type', models.CharField(choices=[('Course', 'Course'), ('Tutorial', 'Tutorial'), ('Book', 'Book'), ('Other', 'Other')], max_length=50)),
                ('platform', models.CharField(choices=[('Udemy', 'Udemy'), ('Coursera', 'Coursera'), ('YouTube', 'YouTube'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('Completed', 'Completed')], max_length=50)),
                ('hours_spent', models.PositiveIntegerField(default=0)),
                ('difficulty_rating', models.IntegerField(default=1)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
